package inheritance.src.main.java;//package inheritance.src.main.java;

import inheritance.src.main.java.Restaurant;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public static void main(String[] args) {
        System.out.println("My name is Ghaida");
        Restaurant resReview1 = new Restaurant("Firefly", 5, 5);
        Review review1 = new Review("its a good restuarant", "Ghaida", 5);
        resReview1.addReview(review1);

        Restaurant resReview2 = new Restaurant("Firefly", 5, 5);
        Review review2 = new Review("its a good restuarant", "Ghaida", 5);
        resReview1.addReview(review1);


//        Restaurant restaurant = new Restaurant();
//        restaurant.name="Mac";

    }}
