/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    Library testObject = new Library();

    @Test public void testMethodS()
    assertEquals(3,testing.roll(3).length);
    assertTrue(testing.containsDuplicates(new int[]{2,2,3,4}));
    assertEquals(3,testing.calculateAvg(new int[]{2,4}));
    assertArrayEquals(new int[]{2,4},testing.lowestaverage(new int[][]{{4,4}, {2, 4}}));

}
