/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inhertince;

import inhertince.Library;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @DisplayName("this tests the ability to instantiate a new restaurant and review object")
    @Test
    void restaurantAndReviewCreation() {
        Restaurant restaurant1 = new Restaurant("KFC", "high");
        assertNotNull(restaurant1);
        assertEquals("KFC",restaurant1.getName());

        Review review1 = new Review("GREAT", "SOME GUY", 3);
        assertEquals("GREAT",review1.getBody());

        Review review2 = new Review("BAD", "SOME GUY", 1);

        restaurant1.addReview(review1);
        restaurant1.addReview(review2);

        assertEquals(2,restaurant1.getStarts());

    }
}
