/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.*;

public class Library {
    public static void main(String[] args) {



    }

    public int[] roll (int rollNumber){
        int [] array =new  int [rollNumber];
        for(int i=0;i<array.length;i++){
            array[i]=(int)(5*Math.random())+1;
        }
        System.out.println(array);
        return array;
    }
    public  boolean containsDuplicates (int [] arr){
        boolean isThereareDuplicates =false;
        for (int i=0;i<arr.length;i++){
            for (int x=i+1;x<arr.length;x++){
                if( arr[i] == arr[x]){
                    isThereareDuplicates=true;
                }
            }
        }
        return isThereareDuplicates;
    }
    public  double calculateAvg (int[] arrays){
        int sum =0;
        for (int i=0;i<arrays.length;i++){
            sum  =sum + arrays[i];
        }
        double avg= (double) sum /arrays.length;
        return avg;

    }
    public  int [] lowestaverage ( int [][] matrixArr){
        ArrayList<Double> avgTemp = new ArrayList<>();
        for(int i=0;i<matrixArr.length;i++){
            double sum =0;
            for (int j=0;j<matrixArr[i].length;j++){
                sum =sum + matrixArr[i][j];
            }
            avgTemp.add(sum/matrixArr[i].length);
        }
        return matrixArr[avgTemp.indexOf(Collections.min(avgTemp))];
    }



    public String weatherData (int [][]arrayMatrix ){
        int maxNum =arrayMatrix[0][0];
        int minNum =arrayMatrix[0][0];
        for (int i=0;i<arrayMatrix.length;i++){
            for (int j=0;j<arrayMatrix.length;j++){
                if(maxNum<= arrayMatrix[i][j]){
                    maxNum=arrayMatrix[i][j];
                }
                else if(maxNum >= arrayMatrix[i][j] ){
                    minNum =arrayMatrix[i][j];
                }
            }
        }
        Set<Integer> temp=new HashSet<>();
        String returnTem= "Max Value =" + maxNum + "Min Value =" + minNum;
        for (int i=0;i<arrayMatrix.length;i++){
            for (int j=0;j<arrayMatrix.length;j++) {
                temp.add(arrayMatrix[i][j]);
            }
        }
        for (int i = minNum; i < maxNum; i++) {
            if (!temp.contains(i)){
                System.out.println ("Never saw temperature: " + i);
            }

        }

        return returnTem;

    }

    public String tally(List<String> list){
        HashSet<String> votedName=new HashSet<String>(list);
        int votes=0;
        String hightVotes=null;
        for (String item:votedName){
            int counter = Collections.frequency(list, item);
            if (votes < counter) {
                votes = counter;
                hightVotes = item;

            }
        }
return hightVotes;

    }



}
